apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: homework
data:
  default.conf: |
    server {
      listen 80;
    
      location /conf/file {
        alias /homework/conf/file;
        default_type text/plain;
      }

      location / {
        root /usr/share/nginx/html;
      }
    }