replicaCount: 3
image:
  repository: nginx
  tag: latest
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  className: nginx
  host: dd-k8s.com
config:
  data:
    key1: value1
    key2: value2
    key3: value3
nginxConfig: |
  server {
    listen 80;
  
    location /conf/file {
      alias /homework/conf/file;
      default_type text/plain;
    }

    location / {
      root /usr/share/nginx/html;
    }
  }
nodeSelector:
  homework: "true"
serviceAccount:
  create: true
  name: monitoring
mysql:
  enabled: false
persistence:
  size: 1Gi  # Добавляем значение по умолчанию